name: "Build Docusaurs"
on:
  workflow_dispatch:
  push:
    branches:
      - docusaurus
jobs:
  build-haddock-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        working-directory: docusaurus
        run: |
          yarn
          yarn build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docusaurus/build
          target-folder: docs
          # We publish our haddock, which is non-trivially big.
          # So keeping the whole history is expensive, and anyway we don't need it.
          single-commit: true
