name: Nightly Test Suite

on:
  push:
    branches:
      - master
      - zliu41/ci
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  nightly-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quick Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: plutus-core-nightly
        if: always()
        run: |
          cd plutus-core
          nix run --no-warn-dirty --accept-flake-config \
            .#hydraJobs.x86_64-linux.ghc92.components.tests.plutus-core.plutus-core-test -- --hedgehog-tests 10000
          cd -

      - name: plutus-ir-nightly
        if: always()
        run: |
          cd plutus-core
          nix run --no-warn-dirty --accept-flake-config \
            .#hydraJobs.x86_64-linux.ghc92.components.tests.plutus-core.plutus-ir-test -- --hedgehog-tests 10000
          cd -
